---
name: Run tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

# cancel previous runs if new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.13

    # only trigger on upstream repo
    if: github.repository == 'neurodatascience/nipoppy-pipeline-configs'

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        allow-prereleases: true

    - name: Install package
      run: |
        pip install -U pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest -ra -q -vv tests/
